#!/usr/bin/env python3
"""
Ingest the "Flames on the Water" book that was processed by breakup_pdf.py
"""

from multi_book_ingest import MultiBookIngest
import json
import os

def ingest_flames_book():
    """Ingest the Flames on the Water book"""
    
    print("🔥 INGESTING: Flames on the Water - Tears in the Sea")
    print("=" * 60)
    
    # Load the metadata generated by breakup_pdf.py
    metadata_file = "./text_files/flames_on_the_water__metadata.json"
    
    if os.path.exists(metadata_file):
        with open(metadata_file, 'r') as f:
            book_metadata = json.load(f)
        print(f"📖 Loaded metadata: {book_metadata['title']} by {book_metadata['author']}")
    else:
        print("⚠️  No metadata file found, using manual info")
        book_metadata = {
            'title': 'Flames on the Water - Tears in the Sea',
            'author': 'Con Aroney',
            'year': None,
            'pages': None
        }
    
    # Create book info for ingestion
    book_info = {
        'title': book_metadata['title'],
        'author': book_metadata['author'],
        'year': book_metadata.get('year', 2022),  # Estimate if not found
        'isbn': book_metadata.get('isbn', ''),
        'publisher': 'Unknown',
        'perspective': 'Australian Greek perspective on Smyrna catastrophe',
        'language': 'English',
        'historical_period': '1922 Greek-Turkish War / Smyrna Fire',
        'description': 'Historical fiction account of the Great Fire of Smyrna from Greek family perspective'
    }
    
    print("\n📚 Book Information:")
    print(f"   Title: {book_info['title']}")
    print(f"   Author: {book_info['author']}")
    print(f"   Perspective: {book_info['perspective']}")
    print(f"   Period: {book_info['historical_period']}")
    
    # Initialize ingester
    ingester = MultiBookIngest()
    
    try:
        # Ingest the book using the section files created by breakup_pdf.py
        file_pattern = "flames_on_the_water__section_*.txt"
        
        print(f"\n🔄 Starting ingestion with pattern: {file_pattern}")
        ingester.ingest_book(book_info, file_pattern)
        
        print("\n✅ INGESTION COMPLETE!")
        print("🔗 Linking to canonical entities...")
        
        # Link to existing canonical entities
        source_id = book_info['title'].lower().replace(' ', '-').replace("'", "")
        source_id = "flames-on-the-water---tears-in-the-sea"  # Clean source ID
        
        ingester.link_to_canonical_entities(source_id)
        
        print("\n🎉 BOOK SUCCESSFULLY ADDED TO DATABASE!")
        print("💡 You can now:")
        print("   • Query both books together")
        print("   • Compare different perspectives on the same events")
        print("   • Run source-aware queries")
        print("   • Update Graphiti for semantic search")
        
    except Exception as e:
        print(f"❌ Ingestion failed: {e}")
        import traceback
        traceback.print_exc()
        
    finally:
        ingester.close()

if __name__ == "__main__":
    ingest_flames_book()